#!/bin/bash

# 🚀 Guide de Démarrage Prisma 6
# Exécutez ce script pour comprendre les étapes de configuration

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🚀 CONFIGURATION PRISMA 6 - GUIDE RAPIDE              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 ÉTAPE 1: Vérifier la Configuration"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "▶ Vérifiez que:"
echo "  1. prisma/schema.prisma - N'a PAS de 'url = env(...)'"
echo "  2. prisma/prisma.config.ts - Contient la DATABASE_URL"
echo "  3. .env.local - Contient DATABASE_URL"
echo ""
echo "Commande:"
echo "  bash check-prisma.sh"
echo ""

echo "📦 ÉTAPE 2: Installer les Dépendances"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm install"
echo ""

echo "🐳 ÉTAPE 3: Démarrer PostgreSQL"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  docker-compose up -d"
echo ""
echo "Vérification:"
echo "  docker-compose ps"
echo ""

echo "🔄 ÉTAPE 4: Générer Prisma Client"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm run prisma:generate"
echo ""

echo "📝 ÉTAPE 5: Créer les Migrations"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm run prisma:migrate"
echo ""
echo "Nommez la migration: 'init'"
echo ""

echo "🌱 ÉTAPE 6: Seed les Données"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm run prisma:seed"
echo ""

echo "🎯 ÉTAPE 7: Vérifier la BD"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm run prisma:studio"
echo ""
echo "Ouvre: http://localhost:5555"
echo ""

echo "🚀 ÉTAPE 8: Démarrer le Dev Server"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Commande:"
echo "  pnpm run dev"
echo ""
echo "Ouvre: http://localhost:3000"
echo ""

echo "═════════════════════════════════════════════════════════════════"
echo "✨ Tests d'API disponibles:"
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "GET    http://localhost:3000/api/users"
echo "POST   http://localhost:3000/api/users"
echo "GET    http://localhost:3000/api/users/1"
echo "PUT    http://localhost:3000/api/users/1"
echo "DELETE http://localhost:3000/api/users/1"
echo ""

echo "📚 RESSOURCES"
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "  - PRISMA_6_CONFIG.md - Configuration détaillée Prisma 6"
echo "  - check-prisma.sh - Vérifier la configuration"
echo "  - README.md - Guide complet du projet"
echo ""

echo "═════════════════════════════════════════════════════════════════"
echo "Bonne chance! 🚀"
echo "═════════════════════════════════════════════════════════════════"
